name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies and Build Code
        run: |
          npm ci --ignore-scripts
          npm run build

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          directory: ./coverage
